name: Data Ingestion Automation

on:
  schedule:
    # Planifie le script pour s'exécuter une fois par jour (ici à 03h00 UTC)
    - cron: "0 3 * * *"

jobs:
  run-data-ingestion:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifie le code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configure l'environnement Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Étape 3 : Installe les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Étape 4 : Lance le script d'insertion
      - name: Run ingestion script
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: python path/to/your_script.py
